# test - h2 setting

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: h2test
    password: h2test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8081
