# MySQL
spring:
  datasource:
    url: jdbc:mysql://billing-system-db.cn4qym2ei1m8.ap-northeast-2.rds.amazonaws.com:3306/biling_system_db
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
#Test H2


  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql : true
      highlight_sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # OAuth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: cf5d57a5a5b6ae7a095aa15e3ade8756
            client-secret: fq37XprPe3cniiMqk8l3GVX86XBAUlzj
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  jwt:
    secret: ${jwt_secret}


#redis
  data:
    redis:
      host: localhost
      port: 6379

# logging
logging:
  level:
    org.hibernate.sql: debug
